apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: level-3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: developer-sa
  namespace: level-3
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
